### ISSUE TITLE
Syntactic sugar

### ISSUE THREAD

**Issue by uasan** [fiberphp/fiber-ext#10]
Current syntax creating Fiber:
```PHP
$task  = function($a, $b){}; // declare handle
$fiber = new Fiber($task);   // instance Fiber
$fiber->resume(1, 2);        // first call handle
$fiber->resume(3);           // subsequent calls 
```
Replace to:
```PHP
async function task($a, $b){}; // declare handle Fiber
$fiber = task(1, 2);           // instance new Fiber and first call handle
$fiber->resume(3);             // subsequent calls 
```
-------------------------

Current syntax yield:
```PHP
$result = Fiber::yield($a + $b);
```
Replace to:
```PHP
$result = await $a + $b;
```
-------------------------

I understand that the Fiber will be used at the level of PHP frameworks, in the userland interface will be an abstract framework API, but still this sugar is easier to write, remember and understand async code.

Thanks.

**Comment by lvht** [comment]
TLTR: No.

---

Fiber is a standalone php module. And it is impossible to add keyword the PHP language by a module.

Adding the keyword `async` and `await` will change the PHP language grammar but offer almost no benefit. It will be hard to persuade the community to accept such change.

---
As the Fiber is on its early stage, there are more work on it's implementation. I think we need to spent all effort on the php kernel land code.
