### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by kelunik** [fiberphp/fiber-ext#13]
Currently there's no license specified.

**Comment by lvht** [comment]
Can a php extension use the MIT license?

**Comment by kelunik** [comment]
It's probably best to use the PHP license if it's intended for submission into the PHP core anyway.

**Comment by lvht** [comment]
fixed by https://github.com/fiberphp/fiber-ext/commit/51bbc2f00e7b2840133d853b5e2a54c0e0a237a4
