### ISSUE TITLE
Fiber::throw(Throwable $exception)

### ISSUE THREAD

**Issue by uasan** [fiberphp/fiber-ext#6]
How to send an exception to Fiber?

In `Generator` has method `throw()`
https://secure.php.net/manual/en/generator.throw.php

I need to do this:
```PHP
function runAsync()
{
    return Fiber::yield('Send network message');
}

$fiber = new Fiber(function()
{
    try
    {
        $c = runAsync();
    }
    catch(Exception $e)
    {
        // Business logic
    }

});

$fiber->resume();

if($isNoblockSocketError = true)
{
    $fiber->throw(new Exception());
}

```

It is possible to implement in Fiber?

Thanks.

**Comment by lvht** [comment]
The `throw` API is not supported now. But may be added in the future if really needed.

**Comment by uasan** [comment]
Yes, it really is necessary, we have a lot of code that using `Generator::throw()`.

By the way in Python Fiber has is this method
https://python-fibers.readthedocs.io/en/latest/#fibers.Fiber.throw

**Comment by uasan** [comment]
He still needs to, cancel the waiting
```PHP
$fiber->throw(new CancelException());
```

**Comment by uasan** [comment]
PhpAmp used `throw()` , this really needed method :)
https://github.com/amphp/amp/blob/05491a57c98bffdd0728477819c2211c0802daeb/lib/Coroutine.php#L71

**Comment by lvht** [comment]
@uasan the `throw` method is not required because you can use `resume` to send any thing and do some check after `yield`.

**Comment by uasan** [comment]
Use it like this?

```PHP
$fiber->resume(new Exception());
```

No, it is much more convenient to use `try catch`, instead of branching off `if(...)` at each call level.

**Comment by lvht** [comment]
it's just a convenience not a requirement

**Comment by uasan** [comment]
> it's just a convenience not a requirement

This is the only reliable way to cancel the continuation of this call stack.
You can not declarations return type from a method.
Without this, Fiber will be difficult to use in FrameWorks `AMP`, `Zend`, `Symfony`...

Look code write in FrameWorks level, if there are no exceptions:
```PHP
function funA($text)
{
    $res = funB('B');

    if(is_string($res))
    {
        return $text.$res;
    }

    return $res;
}

function funB($text)
{
    $res = Fiber::yield();

    if(is_string($res))
    {
        return $text.$res;
    }

    return $res;
}

function run()
{
    $res = funA('A');

    if(is_string($res))
    {
        echo $res;
    }
    else if($res instanceof Exception)
    {
        throw $res;
    }
}

run();

```

This code has method `throw()` in `Fiber`
```PHP
function funA($text):string
{
    return $text.funB('B');
}

function funB($text):string
{
    return $text.Fiber::yield();
}

function run()
{
    echo funA('A');
}

run();
```

**Comment by martinschroeder** [comment]
I think @uasan makes a very valid point about `throw()` preventing you from littering your code with if statements to check if the fiber yielded a value or an error. You can allways check if the yielded value is an instance of `Throwable`, but what about situations where a fiber returns a throwable object that is not an error? (you can work around that using an array containing state and result, but that is an ugly way of doing it)

```php
list ($state, $result) = Fiber::yield();

if ($state == FAILED) {
```

**Comment by martinschroeder** [comment]
One of the coolest use cases for fibers that i can think of would be to bridge promise-based async PHP code to synchronous PHP APIs. A nice example would be to provide a [PSR-7](https://www.php-fig.org/psr/psr-7/) stream implementation backed by an [ReactPHP](https://github.com/reactphp) HTTP client or server.

Promises start pending an resolve eighter with a success value or are rejected with an error. This duality would have a perfect match in a combination of `resume()` and `throw()` methods of a fiber. Using async code from sync code would simply look like this:

```php
try {
  $result = Fiber::yield($somethingAsync->promise());
} catch (Throwable $e) {
  // Deal with that error in case we are interested in it...
}
```
The fiber scheduler would register a callback with the yielded async promise and eighter `resume()` or `throw()` into the Fiber depending on the outcome of the promise.

**Comment by joelwurtz** [comment]
If this is ever implemented, one of the nice thing that can be added would be a double exception : 

 * Exception created and throw by the user on the Fiber
 * An InterruptException (or maybe some other name) which reference the call stack from the Fiber::yield method, which will contain the previous exception as its parent.

So users will have both informations since the exception returned by the user will never be in the context of the yield (since it's interrupted) this will be a nice way to know that this is exception is coming from a specific yield call.

**Comment by lvht** [comment]
The `Fiber::throw(Exception $exception)` has been implemented by https://github.com/fiberphp/fiber-ext/commit/8b695a8bec3b1832b5822fcc127d6f2fa759dae3, but only accept **Exception**.

**Comment by uasan** [comment]
Thank you!

> but only accept Exception.

Correct type checking instance of interface `Throwable `
https://secure.php.net/manual/en/class.throwable.php

For example, class `Error` is not extends class `Exception`, but it implements the interface `Throwable `
```PHP
$fiber->throw(new Error('Test'));  // Fatal error: Uncaught TypeError: Argument 1 passed to Fiber::throw() must be an instance of Exception, instance of Error given
```
