### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by uasan** [fiberphp/fiber-ext#7]
You probably took API from Ruby, but IMHO [Fiber.js](https://github.com/laverdet/node-fibers#api-documentation) better

Method `resume(...$args)`, better rename to `run($arg)` - this short name and always one optional argument.

**Comment by lvht** [comment]
A `Fiber` has a status. When a Fiber is created, it's status the **SUSPENDED**. You need call the `resume` method to **resume** the fiber and it's status will be **RUNNING**. When the fiber finished, it's status will be **FINISHED** and when throw a exception, will be **DEAD**.

So make the resume method named `resume` is more meaningful than the `run`.

**Comment by lvht** [comment]
@uasan And here is the [Lua's coroutine API](https://www.lua.org/pil/9.1.html)

**Comment by joelwurtz** [comment]
But the way what would give calling resume with multiple arguments not on the first run (basically on a yield) ? Does the yield should return an array in that case ? or only the first parameter ?

**Comment by uasan** [comment]
> You need call the resume method to resume the fiber and it's status will be RUNNING.

The status name is `RUNNING`, it means result of calling the `run()` method - it obvious.

First call `resume()` accept many arguments, but subsequent calls only one argument - this is bad design.
