### ISSUE TITLE
Throw exceptions, instead of errors

### ISSUE THREAD

**Issue by uasan** [fiberphp/fiber-ext#8]
Fiber, return errors even in critical cases:
```
Warning: Attempt to resume non suspended Fiber... 
```
I suggest throwing exceptions in such cases.
Exception easy to catch, and norma for style OOP.

Thanks.

**Comment by lvht** [comment]
The **non suspended** here means **finished** or **dead**.

The user land need use the `status` method to get the current status of the fiber, and should not resume a **non suspended** fiber.

If replace the warning with throwing exception, the user land code should catch this exception as well. So output warning or throwing exception is just an issue about coding style. If you prefer using exception, you could convert this warning to exception easily.

**Comment by uasan** [comment]
In my code HTTP server for test Fiber, everywhere the `Fiber::status()` check, looks like redundant

```PHP
if($fiber->status() === Fiber::STATUS_SUSPENDED)
{
    $fiber->resume($data);
}
else
{
    Log::info($error);
}
```

`$fiber->status()` - 99% returns `STATUS_SUSPENDED`, only in very rare cases, for example, the client closes the socket before receiving a response from the server, the status will not be `STATUS_SUSPENDED`.
The much more effective if the Fiber throw exceptions, when the call is called in an invalid status, then the code will become easier:
```PHP
try
{
    $fiber->resume($data);
}
catch(FiberException $error)
{
    Log::info($error);
}
```
We always need to wrap call $fiber->resume() in `try catch` block.
